project_id = "dkxjykxvljppdiaekvwk"

[functions.merchant-create-rider]
verify_jwt = true

[functions.merchant-create-staff]
verify_jwt = true

[functions.billplz-create-bill]
verify_jwt = true

[functions.billplz-webhook]
verify_jwt = false


