project_id = "dkxjykxvljppdiaekvwk"

[functions.merchant-create-rider]
verify_jwt = true

[functions.merchant-create-staff]
verify_jwt = true

[functions.chip-create-purchase]
verify_jwt = true

[functions.chip-webhook]
verify_jwt = false
