project_id = "dkxjykxvljppdiaekvwk"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.chip-create-purchase]
    verify_jwt = true
  [functions.chip-webhook]
    verify_jwt = false
  [functions.merchant-create-rider]
    verify_jwt = true
  [functions.merchant-create-staff]
    verify_jwt = true
  [functions.process-email-queue]
    verify_jwt = true
  [functions.admin-delete-user]
    verify_jwt = true
